import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './Component/Navigation'
import Footer from './Component/Footer'
import { ThemeProvider } from 'next-themes';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider attribute={'class'} enableSystem={true} defaultTheme='system'>
      <Navigation/>

        {children}
        <Footer />
        </ThemeProvider>
        </body>
    </html>
  )
}
